name: CDK Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  cdk-unit-tests:
    name: Run CDK Unit Tests
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run CDK unit tests
        run: npm run test:cdk
        env:
          RPC_URL: https://eth-sepolia.g.alchemy.com/v2/demo
          TREASURY_PUBLIC_ADDRESS: '0x1234567890123456789012345678901234567890'
